"""Add natures table

Revision ID: 2eca95d9bb11
Revises: 145661c4606c
Create Date: 2023-04-07 12:26:51.677245

"""
from alembic import op
import sqlalchemy as sa
from backend.models import Nature


# revision identifiers, used by Alembic.
revision = '2eca95d9bb11'
down_revision = '145661c4606c'
branch_labels = None
depends_on = None

natures = [
    {'name': 'Hardy', 'increased_stat': 'attack', 'decreased_stat': 'attack'},
    {'name': 'Lonely', 'increased_stat': 'attack', 'decreased_stat': 'defense'},
    {'name': 'Brave', 'increased_stat': 'attack', 'decreased_stat': 'speed'},
    {'name': 'Adamant', 'increased_stat': 'attack', 'decreased_stat': 'special-attack'},
    {'name': 'Naughty', 'increased_stat': 'attack', 'decreased_stat': 'special-defense'},
    {'name': 'Bold', 'increased_stat': 'defense', 'decreased_stat': 'attack'},
    {'name': 'Docile', 'increased_stat': 'defense', 'decreased_stat': 'defense'},
    {'name': 'Relaxed', 'increased_stat': 'defense', 'decreased_stat': 'speed'},
    {'name': 'Impish', 'increased_stat': 'defense', 'decreased_stat': 'special-attack'},
    {'name': 'Lax', 'increased_stat': 'defense', 'decreased_stat': 'special-defense'},
    {'name': 'Timid', 'increased_stat': 'speed', 'decreased_stat': 'attack'},
    {'name': 'Hasty', 'increased_stat': 'speed', 'decreased_stat': 'defense'},
    {'name': 'Serious', 'increased_stat': 'speed', 'decreased_stat': 'speed'},
    {'name': 'Jolly', 'increased_stat': 'speed', 'decreased_stat': 'special-attack'},
    {'name': 'Naive', 'increased_stat': 'speed', 'decreased_stat': 'special-defense'},
    {'name': 'Modest', 'increased_stat': 'special-attack', 'decreased_stat': 'attack'},
    {'name': 'Mild', 'increased_stat': 'special-attack', 'decreased_stat': 'defense'},
    {'name': 'Quiet', 'increased_stat': 'special-attack', 'decreased_stat': 'speed'},
    {'name': 'Bashful', 'increased_stat': 'special-attack', 'decreased_stat': 'special-attack'},
    {'name': 'Rash', 'increased_stat': 'special-attack', 'decreased_stat': 'special-defense'},
    {'name': 'Calm', 'increased_stat': 'special-defense', 'decreased_stat': 'attack'},
    {'name': 'Gentle', 'increased_stat': 'special-defense', 'decreased_stat': 'defense'},
    {'name': 'Sassy', 'increased_stat': 'special-defense', 'decreased_stat': 'speed'},
    {'name': 'Careful', 'increased_stat': 'special-defense', 'decreased_stat': 'special-attack'},
    {'name': 'Quirky', 'increased_stat': 'special-defense', 'decreased_stat': 'special-defense'},
]

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('increased_stat', sa.String(length=20), nullable=False),
    sa.Column('decreased_stat', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    for nature in natures:
        op.execute(f"INSERT INTO nature (name, increased_stat, decreased_stat) VALUES ('{nature['name']}', '{nature['increased_stat']}', '{nature['decreased_stat']}')")
    
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    op.drop_table('nature')
    # ### end Alembic commands ###
