"""Add Types table

Revision ID: 3d797ae00858
Revises: 0fe04cb7c2db
Create Date: 2023-07-19 23:31:13.559325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d797ae00858'
down_revision = '0fe04cb7c2db'
branch_labels = None
depends_on = None

types = [
    {'name': 'normal', 'type_id': 1},
    {'name': 'fighting', 'type_id': 2},
    {'name': 'flying', 'type_id': 3},
    {'name': 'poison', 'type_id': 4},
    {'name': 'ground', 'type_id': 5},
    {'name': 'rock', 'type_id': 6},
    {'name': 'bug', 'type_id': 7},
    {'name': 'ghost', 'type_id': 8},
    {'name': 'steel', 'type_id': 9},
    {'name': 'fire', 'type_id': 10},
    {'name': 'water', 'type_id': 11},
    {'name': 'grass', 'type_id': 12},
    {'name': 'electric', 'type_id': 13},
    {'name': 'psychic', 'type_id': 14},
    {'name': 'ice', 'type_id': 15},
    {'name': 'dragon', 'type_id': 16},
    {'name': 'dark', 'type_id': 17},
    {'name': 'fairy', 'type_id': 18},
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    for type in types:
        op.execute(f"INSERT INTO type (name, type_id) VALUES ('{type['name']}', '{type['type_id']}')")
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('type')
    # ### end Alembic commands ###
