"""Add Level to team pokemon

Revision ID: 89b2d75d415f
Revises: 0b19beed7599
Create Date: 2024-01-24 02:32:31.045700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b2d75d415f'
down_revision = '0b19beed7599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'type', ['tera_type_id'], ['id'])
    
    op.execute("UPDATE team_pokemon SET level = 50 WHERE level IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_pokemon', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('level')

    # ### end Alembic commands ###
