"""Adding Egg Groups

Revision ID: a340d3c1b6cb
Revises: b5e7a7d61139
Create Date: 2023-10-21 22:27:14.553228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a340d3c1b6cb'
down_revision = 'b5e7a7d61139'
branch_labels = None
depends_on = None

egg_groups = [
    {'name': 'monster', 'egg_group_id': 1},
    {'name': 'water-1', 'egg_group_id': 2},
    {'name': 'bug', 'egg_group_id': 3},
    {'name': 'flying', 'egg_group_id': 4},
    {'name': 'field', 'egg_group_id': 5},
    {'name': 'fairy', 'egg_group_id': 6},
    {'name': 'grass', 'egg_group_id': 7},
    {'name': 'human-like', 'egg_group_id': 8},
    {'name': 'water-3', 'egg_group_id': 9},
    {'name': 'mineral', 'egg_group_id': 10},
    {'name': 'amorphous', 'egg_group_id': 11},
    {'name': 'water-2', 'egg_group_id': 12},
    {'name': 'ditto', 'egg_group_id': 13},
    {'name': 'dragon', 'egg_group_id': 14},
    {'name': 'no-eggs', 'egg_group_id': 15},
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('egg_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('egg_group_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    for egg_group in egg_groups:
        op.execute(f"INSERT INTO egg_group (name, egg_group_id) VALUES ('{egg_group['name']}', '{egg_group['egg_group_id']}')")
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('egg_group')
    # ### end Alembic commands ###
