"""Added is active to User_Pokemon Relation

Revision ID: f2ba5b59f9f7
Revises: 2eca95d9bb11
Create Date: 2023-04-13 15:30:03.600777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ba5b59f9f7'
down_revision = '2eca95d9bb11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pokemon', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
